# Generated by Django 5.2.6 on 2025-10-05 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used in the package URL.', max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hello.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'package')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='hello_booki_status_e987d8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='hello_booki_travel__1570e7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='hello_booki_booking_939845_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['slug'], name='hello_packa_slug_262865_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'is_available'], name='hello_packa_categor_48e273_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='hello_revie_rating_f13e22_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='hello_revie_created_cad9bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_people__gte', 1)), name='booking_people_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_gte_0'),
        ),
    ]
