# Generated by Django 5.2.6 on 2025-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_package_slug_alter_booking_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(help_text='Used in the package URL.', max_length=220, unique=True),
        ),
    ]
